### ISSUE TITLE
Always bad signature with nested routes in rack

### ISSUE THREAD

**Issue by spuun** [manifoldco/ruby-manifoldco-signature#5]
I had problem with signature verification failing all the time. After some time i found out that `ManifoldcoSignature:: Signature::canonize()` probably should use `request.path` instead of `request.path_info` since path_info is reduced for each route level.

Example to reproduce:
https://gist.github.com/spuun/57ef3752aae692fd2cf3c7eea27a4be2

**Comment by jbowes** [comment]
You're right! Thanks for the report.

**Comment by jbowes** [comment]
v0.1.4 is live now on rubygems with this fix. thanks again!
